name:                parallel-asm
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- filepath
- hashable
- split
- unordered-containers
- vector

library:
  source-dirs: src

executables:
  parallel-asm-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parallel-asm

tests:
  parallel-asm-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parallel-asm
